version: '3.1'
services:

  stat-database:
    image: postgres:15.4
    container_name: ewm-stat-database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready -q -d ewm_stat -U postgres"
      interval: 2s
      timeout: 2s
      retries: 5